"""initial_schema_47_tables

Revision ID: 704441bfafad
Revises: 
Create Date: 2026-09-20 13:26:54.001837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '704441bfafad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure required extensions exist
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'vector') THEN
                CREATE EXTENSION IF NOT EXISTS vector;
            END IF;
        END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('industry_domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('idx_career_roles_slug', 'career_roles', ['slug'], unique=False)
    op.create_index(op.f('ix_career_roles_slug'), 'career_roles', ['slug'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry_type', sa.String(length=100), nullable=False),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('headquarters', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_companies_industry_type', 'companies', ['industry_type'], unique=False)
    op.create_index('idx_companies_name', 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_industry_type'), 'companies', ['industry_type'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model_name', sa.String(length=100), server_default=sa.text("'text-embedding-3-small'"), nullable=False),
    sa.Column('model_version', sa.String(length=100), server_default=sa.text("'1.0'"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_entity_embedding')
    )
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
                CREATE INDEX IF NOT EXISTS idx_embeddings_cosine ON embeddings USING hnsw (embedding_vector vector_cosine_ops);
            END IF;
        END $$;
    """)
    op.create_index('idx_embeddings_lookup', 'embeddings', ['entity_type', 'entity_id'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('institution_type', sa.String(length=50), server_default=sa.text("'COLLEGE'"), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('is_accredited', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_institutions_code', 'institutions', ['code'], unique=False)
    op.create_index('idx_institutions_state_city', 'institutions', ['state', 'city'], unique=False)
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_skills_category', 'skills', ['category'], unique=False)
    op.create_index('idx_skills_slug', 'skills', ['slug'], unique=False)
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_or_url', sa.Text(), nullable=True),
    sa.Column('conducted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('end_time >= start_time', name='chk_activities_times'),
    sa.ForeignKeyConstraint(['conducted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_institution', 'activities', ['institution_id'], unique=False)
    op.create_index('idx_activities_start_time', 'activities', ['start_time'], unique=False)
    op.create_index(op.f('ix_activities_institution_id'), 'activities', ['institution_id'], unique=False)
    op.create_index(op.f('ix_activities_start_time'), 'activities', ['start_time'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_skill_id', sa.UUID(), nullable=True),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('60.00'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='chk_assessments_duration'),
    sa.CheckConstraint('passing_score >= 0.00 AND passing_score <= 100.00', name='chk_assessments_passing_score'),
    sa.CheckConstraint('total_questions > 0', name='chk_assessments_total_q'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessments_company', 'assessments', ['company_id'], unique=False)
    op.create_index('idx_assessments_skill', 'assessments', ['target_skill_id'], unique=False)
    op.create_index(op.f('ix_assessments_company_id'), 'assessments', ['company_id'], unique=False)
    op.create_index(op.f('ix_assessments_target_skill_id'), 'assessments', ['target_skill_id'], unique=False)
    op.create_table('career_role_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('career_role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('required_level', sa.String(length=50), nullable=False),
    sa.Column('importance_level', sa.String(length=50), server_default=sa.text("'CORE'"), nullable=False),
    sa.ForeignKeyConstraint(['career_role_id'], ['career_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_role_id', 'skill_id', name='uq_career_role_skill')
    )
    op.create_index('idx_career_role_skills_role', 'career_role_skills', ['career_role_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=50), server_default=sa.text("'GENERAL'"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_posts_author', 'community_posts', ['author_user_id'], unique=False)
    op.create_index('idx_community_posts_created', 'community_posts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_community_posts_author_user_id'), 'community_posts', ['author_user_id'], unique=False)
    op.create_table('company_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('hr_role', sa.String(length=50), server_default=sa.text("'RECRUITER'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_users_company_id', 'company_users', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_users_company_id'), 'company_users', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_users_user_id'), 'company_users', ['user_id'], unique=True)
    op.create_table('competitions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('organizer_type', sa.String(length=50), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('track_type', sa.String(length=50), server_default=sa.text("'BOTH'"), nullable=False),
    sa.Column('max_team_size', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('prizes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'UPCOMING'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date AND start_date >= registration_deadline', name='chk_competitions_dates'),
    sa.CheckConstraint('max_team_size > 0', name='chk_competitions_team_size'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_competitions_slug', 'competitions', ['slug'], unique=False)
    op.create_index('idx_competitions_status', 'competitions', ['status'], unique=False)
    op.create_index(op.f('ix_competitions_slug'), 'competitions', ['slug'], unique=True)
    op.create_index(op.f('ix_competitions_status'), 'competitions', ['status'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_institution_department_code'),
    sa.UniqueConstraint('institution_id', 'id', name='uq_institution_department_id')
    )
    op.create_index('idx_departments_institution_id', 'departments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_departments_institution_id'), 'departments', ['institution_id'], unique=False)
    op.create_table('institution_staff',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('staff_role', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_institution_staff_inst_role', 'institution_staff', ['institution_id', 'staff_role'], unique=False)
    op.create_index(op.f('ix_institution_staff_institution_id'), 'institution_staff', ['institution_id'], unique=False)
    op.create_index(op.f('ix_institution_staff_user_id'), 'institution_staff', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('is_remote', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('stipend_salary', sa.String(length=100), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('openings_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('eligibility_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_months IS NULL OR duration_months > 0', name='chk_opportunities_duration'),
    sa.CheckConstraint('openings_count > 0', name='chk_opportunities_openings'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opportunities_company', 'opportunities', ['company_id'], unique=False)
    op.create_index('idx_opportunities_status_deadline', 'opportunities', ['status', 'application_deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_table('skill_relationships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_skill_id', sa.UUID(), nullable=False),
    sa.Column('child_skill_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.CheckConstraint('parent_skill_id != child_skill_id', name='chk_no_self_relationship'),
    sa.ForeignKeyConstraint(['child_skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_skill_id', 'child_skill_id', 'relationship_type', name='uq_skill_relationship')
    )
    op.create_index('idx_skill_rel_child', 'skill_relationships', ['child_skill_id'], unique=False)
    op.create_index('idx_skill_rel_parent', 'skill_relationships', ['parent_skill_id'], unique=False)
    op.create_table('training_programs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('program_type', sa.String(length=50), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('conducted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'UPCOMING'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('capacity IS NULL OR capacity > 0', name='chk_training_programs_capacity'),
    sa.CheckConstraint('end_date >= start_date', name='chk_training_programs_dates'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conducted_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_programs_dates', 'training_programs', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_training_programs_institution', 'training_programs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_training_programs_institution_id'), 'training_programs', ['institution_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('points > 0', name='chk_assessment_questions_points'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessment_questions_assessment', 'assessment_questions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['community_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_comments_post', 'community_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_table('opportunity_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('required_proficiency', sa.String(length=50), server_default=sa.text("'INTERMEDIATE'"), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'skill_id', name='uq_opportunity_skill')
    )
    op.create_index('idx_opp_skills_opp_id', 'opportunity_skills', ['opportunity_id'], unique=False)
    op.create_table('placement_interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('conducted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['conducted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_placement_interactions_opp', 'placement_interactions', ['opportunity_id'], unique=False)
    op.create_index('idx_placement_interactions_schedule', 'placement_interactions', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_placement_interactions_opportunity_id'), 'placement_interactions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_placement_interactions_scheduled_at'), 'placement_interactions', ['scheduled_at'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('enrollment_year', sa.Integer(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('target_career_role_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cgpa IS NULL OR (cgpa >= 0.00 AND cgpa <= 10.00)', name='chk_students_cgpa'),
    sa.CheckConstraint('current_semester > 0', name='chk_students_semester'),
    sa.CheckConstraint('graduation_year >= enrollment_year', name='chk_students_graduation'),
    sa.ForeignKeyConstraint(['institution_id', 'department_id'], ['departments.institution_id', 'departments.id'], name='fk_student_institution_dept', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_career_role_id'], ['career_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'roll_number', name='uq_institution_student_roll')
    )
    op.create_index('idx_students_graduation_year', 'students', ['graduation_year'], unique=False)
    op.create_index('idx_students_institution_dept', 'students', ['institution_id', 'department_id'], unique=False)
    op.create_index('idx_students_target_role', 'students', ['target_career_role_id'], unique=False)
    op.create_index(op.f('ix_students_graduation_year'), 'students', ['graduation_year'], unique=False)
    op.create_index(op.f('ix_students_target_career_role_id'), 'students', ['target_career_role_id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('is_trainer', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id', 'department_id'], ['departments.institution_id', 'departments.id'], name='fk_teacher_institution_dept', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teachers_institution_dept', 'teachers', ['institution_id', 'department_id'], unique=False)
    op.create_index('idx_teachers_is_trainer', 'teachers', ['is_trainer'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.create_table('assessment_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('percentage >= 0.00 AND percentage <= 100.00', name='chk_assessment_attempts_pct'),
    sa.CheckConstraint('score >= 0.00', name='chk_assessment_attempts_score'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessment_attempts_assessment', 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_attempts_student', 'assessment_attempts', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_assessment_id'), 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_student_id'), 'assessment_attempts', ['student_id'], unique=False)
    op.create_table('competition_participants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('submission_url', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('award_title', sa.String(length=150), nullable=True),
    sa.Column('certificate_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'student_id', name='uq_comp_participant')
    )
    op.create_index('idx_comp_participants_comp', 'competition_participants', ['competition_id'], unique=False)
    op.create_index('idx_comp_participants_student', 'competition_participants', ['student_id'], unique=False)
    op.create_table('competition_teams',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(length=150), nullable=False),
    sa.Column('team_leader_student_id', sa.UUID(), nullable=False),
    sa.Column('submission_url', sa.Text(), nullable=True),
    sa.Column('submission_notes', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('award_title', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_leader_student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'team_name', name='uq_comp_team_name')
    )
    op.create_index('idx_comp_teams_competition', 'competition_teams', ['competition_id'], unique=False)
    op.create_table('internships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('supervisor_user_id', sa.UUID(), nullable=True),
    sa.Column('supervisor_name', sa.String(length=150), nullable=False),
    sa.Column('supervisor_email', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('stipend', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'ONGOING'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='chk_internships_dates'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_internships_company', 'internships', ['company_id'], unique=False)
    op.create_index('idx_internships_student', 'internships', ['student_id'], unique=False)
    op.create_index('idx_internships_supervisor', 'internships', ['supervisor_user_id'], unique=False)
    op.create_index(op.f('ix_internships_supervisor_user_id'), 'internships', ['supervisor_user_id'], unique=False)
    op.create_table('mentor_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('mentor_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'mentor_user_id', name='uq_student_mentor_connection')
    )
    op.create_index('idx_mentor_conn_mentor', 'mentor_connections', ['mentor_user_id'], unique=False)
    op.create_index('idx_mentor_conn_student', 'mentor_connections', ['student_id'], unique=False)
    op.create_index(op.f('ix_mentor_connections_mentor_user_id'), 'mentor_connections', ['mentor_user_id'], unique=False)
    op.create_index(op.f('ix_mentor_connections_student_id'), 'mentor_connections', ['student_id'], unique=False)
    op.create_table('peer_skill_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('requester_student_id', sa.UUID(), nullable=False),
    sa.Column('helper_student_id', sa.UUID(), nullable=True),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['helper_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_peer_skill_req_skill', 'peer_skill_requests', ['skill_id'], unique=False)
    op.create_index('idx_peer_skill_req_status', 'peer_skill_requests', ['status'], unique=False)
    op.create_index(op.f('ix_peer_skill_requests_skill_id'), 'peer_skill_requests', ['skill_id'], unique=False)
    op.create_index(op.f('ix_peer_skill_requests_status'), 'peer_skill_requests', ['status'], unique=False)
    op.create_table('placement_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('package_lpa', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('offer_letter_url', sa.Text(), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'OFFERED'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('package_lpa > 0.00', name='chk_placement_package'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_placement_records_institution', 'placement_records', ['institution_id'], unique=False)
    op.create_index('idx_placement_records_student', 'placement_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_placement_records_institution_id'), 'placement_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_placement_records_student_id'), 'placement_records', ['student_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repository_url', sa.Text(), nullable=True),
    sa.Column('live_url', sa.Text(), nullable=True),
    sa.Column('role_in_project', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_items_student', 'portfolio_items', ['student_id'], unique=False)
    op.create_index(op.f('ix_portfolio_items_student_id'), 'portfolio_items', ['student_id'], unique=False)
    op.create_table('recognitions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuer_name', sa.String(length=255), nullable=False),
    sa.Column('issuer_type', sa.String(length=50), nullable=False),
    sa.Column('badge_icon', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('verification_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_hash')
    )
    op.create_index('idx_recognitions_student', 'recognitions', ['student_id'], unique=False)
    op.create_index(op.f('ix_recognitions_student_id'), 'recognitions', ['student_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['career_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resume_versions_student', 'resume_versions', ['student_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_student_id'), 'resume_versions', ['student_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('career_role_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_role_id'], ['career_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roadmaps_student', 'roadmaps', ['student_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('career_role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('current_level', sa.String(length=50), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('target_level', sa.String(length=50), nullable=False),
    sa.Column('gap_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calculated_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['career_role_id'], ['career_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'career_role_id', 'skill_id', name='uq_student_role_skill_gap')
    )
    op.create_index('idx_skill_gaps_student_role', 'skill_gaps', ['student_id', 'career_role_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), server_default=sa.text("'BEGINNER'"), nullable=False),
    sa.Column('verification_status', sa.String(length=50), server_default=sa.text("'SELF_REPORTED'"), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0.00 AND confidence_score <= 1.00)', name='chk_student_skills_conf'),
    sa.CheckConstraint('score IS NULL OR (score >= 0.00 AND score <= 100.00)', name='chk_student_skills_score'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'skill_id', name='uq_student_skill')
    )
    op.create_index('idx_student_skills_lookup', 'student_skills', ['student_id', 'skill_id'], unique=False)
    op.create_index('idx_student_skills_status', 'student_skills', ['verification_status'], unique=False)
    op.create_table('training_enrollments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('training_program_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('attendance_percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('completion_status', sa.String(length=50), server_default=sa.text("'ENROLLED'"), nullable=False),
    sa.Column('certificate_url', sa.Text(), nullable=True),
    sa.CheckConstraint('attendance_percentage >= 0.00 AND attendance_percentage <= 100.00', name='chk_training_enrollments_att'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_program_id', 'student_id', name='uq_training_enrollment')
    )
    op.create_index('idx_training_enrollments_student', 'training_enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_training_enrollments_student_id'), 'training_enrollments', ['student_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=50), server_default=sa.text("'APPLIED'"), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'student_id', name='uq_student_opportunity_application')
    )
    op.create_index('idx_applications_opportunity_status', 'applications', ['opportunity_id', 'current_status'], unique=False)
    op.create_index('idx_applications_student', 'applications', ['student_id'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('competition_team_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('member_role', sa.String(length=50), server_default=sa.text("'DEVELOPER'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['competition_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'student_id', name='uq_team_student_member')
    )
    op.create_index('idx_comp_team_members_student', 'competition_team_members', ['student_id'], unique=False)
    op.create_index('idx_comp_team_members_team', 'competition_team_members', ['team_id'], unique=False)
    op.create_table('internship_evaluations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('internship_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_user_id', sa.UUID(), nullable=True),
    sa.Column('technical_rating', sa.Integer(), nullable=False),
    sa.Column('soft_skills_rating', sa.Integer(), nullable=False),
    sa.Column('punctuality_rating', sa.Integer(), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('punctuality_rating BETWEEN 1 AND 5', name='chk_eval_punc_rating'),
    sa.CheckConstraint('soft_skills_rating BETWEEN 1 AND 5', name='chk_eval_soft_rating'),
    sa.CheckConstraint('technical_rating BETWEEN 1 AND 5', name='chk_eval_tech_rating'),
    sa.ForeignKeyConstraint(['evaluator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_internship_evaluations_internship', 'internship_evaluations', ['internship_id'], unique=False)
    op.create_index(op.f('ix_internship_evaluations_internship_id'), 'internship_evaluations', ['internship_id'], unique=True)
    op.create_table('internship_progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('internship_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('mentor_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('week_number > 0', name='chk_internship_progress_week'),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internship_id', 'week_number', name='uq_internship_week_report')
    )
    op.create_index('idx_internship_progress_internship', 'internship_progress', ['internship_id'], unique=False)
    op.create_index(op.f('ix_internship_progress_internship_id'), 'internship_progress', ['internship_id'], unique=False)
    op.create_table('mentorship_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default=sa.text('45'), nullable=False),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'SCHEDULED'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='chk_session_duration'),
    sa.CheckConstraint('feedback_rating IS NULL OR (feedback_rating >= 1 AND feedback_rating <= 5)', name='chk_session_feedback'),
    sa.ForeignKeyConstraint(['connection_id'], ['mentor_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mentorship_sessions_conn', 'mentorship_sessions', ['connection_id'], unique=False)
    op.create_index('idx_mentorship_sessions_time', 'mentorship_sessions', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_mentorship_sessions_connection_id'), 'mentorship_sessions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_mentorship_sessions_scheduled_at'), 'mentorship_sessions', ['scheduled_at'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_url', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('estimated_hours IS NULL OR estimated_hours >= 0', name='chk_roadmap_items_hours'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'step_order', name='uq_roadmap_item_order')
    )
    op.create_index('idx_roadmap_items_roadmap', 'roadmap_items', ['roadmap_id'], unique=False)
    op.create_table('skill_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_skill_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['student_skill_id'], ['student_skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skill_evidence_ref', 'skill_evidence', ['evidence_type', 'reference_id'], unique=False)
    op.create_index('idx_skill_evidence_student_skill', 'skill_evidence', ['student_skill_id'], unique=False)
    op.create_table('application_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_status_hist_application', 'application_status_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_index('idx_app_status_hist_application', table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index('idx_skill_evidence_student_skill', table_name='skill_evidence')
    op.drop_index('idx_skill_evidence_ref', table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_index('idx_roadmap_items_roadmap', table_name='roadmap_items')
    op.drop_table('roadmap_items')
    op.drop_index(op.f('ix_mentorship_sessions_scheduled_at'), table_name='mentorship_sessions')
    op.drop_index(op.f('ix_mentorship_sessions_connection_id'), table_name='mentorship_sessions')
    op.drop_index('idx_mentorship_sessions_time', table_name='mentorship_sessions')
    op.drop_index('idx_mentorship_sessions_conn', table_name='mentorship_sessions')
    op.drop_table('mentorship_sessions')
    op.drop_index(op.f('ix_internship_progress_internship_id'), table_name='internship_progress')
    op.drop_index('idx_internship_progress_internship', table_name='internship_progress')
    op.drop_table('internship_progress')
    op.drop_index(op.f('ix_internship_evaluations_internship_id'), table_name='internship_evaluations')
    op.drop_index('idx_internship_evaluations_internship', table_name='internship_evaluations')
    op.drop_table('internship_evaluations')
    op.drop_index('idx_comp_team_members_team', table_name='competition_team_members')
    op.drop_index('idx_comp_team_members_student', table_name='competition_team_members')
    op.drop_table('competition_team_members')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index('idx_applications_student', table_name='applications')
    op.drop_index('idx_applications_opportunity_status', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_training_enrollments_student_id'), table_name='training_enrollments')
    op.drop_index('idx_training_enrollments_student', table_name='training_enrollments')
    op.drop_table('training_enrollments')
    op.drop_index('idx_student_skills_status', table_name='student_skills')
    op.drop_index('idx_student_skills_lookup', table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index('idx_skill_gaps_student_role', table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index('idx_roadmaps_student', table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_resume_versions_student_id'), table_name='resume_versions')
    op.drop_index('idx_resume_versions_student', table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_recognitions_student_id'), table_name='recognitions')
    op.drop_index('idx_recognitions_student', table_name='recognitions')
    op.drop_table('recognitions')
    op.drop_index(op.f('ix_portfolio_items_student_id'), table_name='portfolio_items')
    op.drop_index('idx_portfolio_items_student', table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_placement_records_student_id'), table_name='placement_records')
    op.drop_index(op.f('ix_placement_records_institution_id'), table_name='placement_records')
    op.drop_index('idx_placement_records_student', table_name='placement_records')
    op.drop_index('idx_placement_records_institution', table_name='placement_records')
    op.drop_table('placement_records')
    op.drop_index(op.f('ix_peer_skill_requests_status'), table_name='peer_skill_requests')
    op.drop_index(op.f('ix_peer_skill_requests_skill_id'), table_name='peer_skill_requests')
    op.drop_index('idx_peer_skill_req_status', table_name='peer_skill_requests')
    op.drop_index('idx_peer_skill_req_skill', table_name='peer_skill_requests')
    op.drop_table('peer_skill_requests')
    op.drop_index(op.f('ix_mentor_connections_student_id'), table_name='mentor_connections')
    op.drop_index(op.f('ix_mentor_connections_mentor_user_id'), table_name='mentor_connections')
    op.drop_index('idx_mentor_conn_student', table_name='mentor_connections')
    op.drop_index('idx_mentor_conn_mentor', table_name='mentor_connections')
    op.drop_table('mentor_connections')
    op.drop_index(op.f('ix_internships_supervisor_user_id'), table_name='internships')
    op.drop_index('idx_internships_supervisor', table_name='internships')
    op.drop_index('idx_internships_student', table_name='internships')
    op.drop_index('idx_internships_company', table_name='internships')
    op.drop_table('internships')
    op.drop_index('idx_comp_teams_competition', table_name='competition_teams')
    op.drop_table('competition_teams')
    op.drop_index('idx_comp_participants_student', table_name='competition_participants')
    op.drop_index('idx_comp_participants_comp', table_name='competition_participants')
    op.drop_table('competition_participants')
    op.drop_index(op.f('ix_assessment_attempts_student_id'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_assessment_id'), table_name='assessment_attempts')
    op.drop_index('idx_assessment_attempts_student', table_name='assessment_attempts')
    op.drop_index('idx_assessment_attempts_assessment', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index('idx_teachers_is_trainer', table_name='teachers')
    op.drop_index('idx_teachers_institution_dept', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_target_career_role_id'), table_name='students')
    op.drop_index(op.f('ix_students_graduation_year'), table_name='students')
    op.drop_index('idx_students_target_role', table_name='students')
    op.drop_index('idx_students_institution_dept', table_name='students')
    op.drop_index('idx_students_graduation_year', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_placement_interactions_scheduled_at'), table_name='placement_interactions')
    op.drop_index(op.f('ix_placement_interactions_opportunity_id'), table_name='placement_interactions')
    op.drop_index('idx_placement_interactions_schedule', table_name='placement_interactions')
    op.drop_index('idx_placement_interactions_opp', table_name='placement_interactions')
    op.drop_table('placement_interactions')
    op.drop_index('idx_opp_skills_opp_id', table_name='opportunity_skills')
    op.drop_table('opportunity_skills')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.drop_index('idx_community_comments_post', table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_index('idx_assessment_questions_assessment', table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_training_programs_institution_id'), table_name='training_programs')
    op.drop_index('idx_training_programs_institution', table_name='training_programs')
    op.drop_index('idx_training_programs_dates', table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_index('idx_skill_rel_parent', table_name='skill_relationships')
    op.drop_index('idx_skill_rel_child', table_name='skill_relationships')
    op.drop_table('skill_relationships')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_index('idx_opportunities_status_deadline', table_name='opportunities')
    op.drop_index('idx_opportunities_company', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_institution_staff_user_id'), table_name='institution_staff')
    op.drop_index(op.f('ix_institution_staff_institution_id'), table_name='institution_staff')
    op.drop_index('idx_institution_staff_inst_role', table_name='institution_staff')
    op.drop_table('institution_staff')
    op.drop_index(op.f('ix_departments_institution_id'), table_name='departments')
    op.drop_index('idx_departments_institution_id', table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_competitions_status'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_slug'), table_name='competitions')
    op.drop_index('idx_competitions_status', table_name='competitions')
    op.drop_index('idx_competitions_slug', table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_company_users_user_id'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_company_id'), table_name='company_users')
    op.drop_index('idx_company_users_company_id', table_name='company_users')
    op.drop_table('company_users')
    op.drop_index(op.f('ix_community_posts_author_user_id'), table_name='community_posts')
    op.drop_index('idx_community_posts_created', table_name='community_posts')
    op.drop_index('idx_community_posts_author', table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index('idx_career_role_skills_role', table_name='career_role_skills')
    op.drop_table('career_role_skills')
    op.drop_index(op.f('ix_assessments_target_skill_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_company_id'), table_name='assessments')
    op.drop_index('idx_assessments_skill', table_name='assessments')
    op.drop_index('idx_assessments_company', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_activities_start_time'), table_name='activities')
    op.drop_index(op.f('ix_activities_institution_id'), table_name='activities')
    op.drop_index('idx_activities_start_time', table_name='activities')
    op.drop_index('idx_activities_institution', table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_index('idx_skills_slug', table_name='skills')
    op.drop_index('idx_skills_category', table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_index('idx_institutions_state_city', table_name='institutions')
    op.drop_index('idx_institutions_code', table_name='institutions')
    op.drop_table('institutions')
    op.drop_index('idx_embeddings_lookup', table_name='embeddings')
    op.execute("DROP INDEX IF EXISTS idx_embeddings_cosine;")
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry_type'), table_name='companies')
    op.drop_index('idx_companies_name', table_name='companies')
    op.drop_index('idx_companies_industry_type', table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_career_roles_slug'), table_name='career_roles')
    op.drop_index('idx_career_roles_slug', table_name='career_roles')
    op.drop_table('career_roles')
    # ### end Alembic commands ###
